from __future__ import annotations

from typing import Any

from app.core.config import INTENT_PROMPTS
from app.models.schemas import KnowledgeHit, ReplyDraft, ReplyGenerateRequest
from app.services.llm_gateway import LlmGateway


class ReplyService:
    def __init__(self, llm_gateway: LlmGateway | None = None) -> None:
        self.llm_gateway = llm_gateway or LlmGateway()

    async def generate(
        self,
        request: ReplyGenerateRequest,
        prompt_overrides: dict[str, Any] | None = None,
        runtime_config: dict[str, Any] | None = None,
    ) -> ReplyDraft:
        prompts = prompt_overrides or INTENT_PROMPTS
        prompt_config = prompts.get(request.intent, prompts["其他"])
        knowledge_hits = [
            KnowledgeHit.model_validate(hit) if isinstance(hit, dict) else hit
            for hit in request.knowledge_hits
        ]
        cited_ids = [item.doc_id for item in knowledge_hits]

        llm_reply = await self.llm_gateway.generate_reply(
            intent=request.intent,
            user_message=request.user_message,
            instructions=prompt_config["instructions"],
            knowledge_context=[item.model_dump() for item in knowledge_hits],
            conversation_history=request.conversation_history,
            runtime_config=runtime_config,
        )

        return ReplyDraft(
            draft_reply=llm_reply,
            prompt_template=prompt_config["template_name"],
            cited_knowledge_ids=cited_ids,
            risk_notes=[
                "Generated by required LLM runtime.",
                prompt_config["instructions"],
            ],
            model_name=(runtime_config or {}).get("llm_model", "llm-runtime"),
        )
